import type { Metadata } from "next";
import { Poppins, Karla, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import clsx from "clsx";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: [ "200", "300", "400", "500", "600", "700", "800"],
});
const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  weight: [ "200", "300", "400", "500", "600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(bricolage.variable ,karla.className , poppins.variable, 'bg-white')}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
